package app

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"dbrain/internal/categoryvocab"
	"dbrain/internal/store"
)

func newCategorizeAnalyzeCommand(root *rootOptions) *cobra.Command {
	var minCount int
	var sortAlpha bool
	var draft bool

	cmd := &cobra.Command{
		Use:   "analyze",
		Short: "Show tag/category frequency to help author categories.yaml",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := loadConfig(root.root)
			if err != nil {
				return err
			}
			st, err := store.Open(cfg.DBPath)
			if err != nil {
				return err
			}
			defer func() { _ = st.Close() }()

			items, err := st.ListCategorizedItems(cmd.Context())
			if err != nil {
				return err
			}

			// Count every token across all user_tags.
			counts := make(map[string]int)
			for _, item := range items {
				for _, t := range strings.Split(item.UserTags, ",") {
					t = strings.TrimSpace(t)
					if t != "" {
						counts[t]++
					}
				}
			}

			// Apply existing vocab so analysis reflects current state.
			vocabPath := filepath.Join(cfg.RootDir, "categories.yaml")
			vocab, _ := categoryvocab.Load(vocabPath)

			if draft {
				return writeDraftYAML(cmd, counts, vocab, minCount)
			}

			type entry struct {
				token string
				count int
			}
			entries := make([]entry, 0, len(counts))
			for t, c := range counts {
				if c >= minCount {
					entries = append(entries, entry{t, c})
				}
			}

			if sortAlpha {
				sort.Slice(entries, func(i, j int) bool {
					return entries[i].token < entries[j].token
				})
			} else {
				sort.Slice(entries, func(i, j int) bool {
					if entries[i].count != entries[j].count {
						return entries[i].count > entries[j].count
					}
					return entries[i].token < entries[j].token
				})
			}

			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Categorized items: %d\nUnique tokens (count >= %d): %d\n\n",
				len(items), minCount, len(entries))

			for _, e := range entries {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "%5d  %s\n", e.count, e.token)
			}
			return nil
		},
	}

	cmd.Flags().IntVar(&minCount, "min-count", 2, "Only show tokens appearing this many times or more")
	cmd.Flags().BoolVar(&sortAlpha, "alpha", false, "Sort alphabetically instead of by frequency")
	cmd.Flags().BoolVar(&draft, "draft", false, "Write a starter categories.yaml to stdout based on detected clusters")

	return cmd
}

// writeDraftYAML finds definitive aliases (tokens that are identical after
// case/space/hyphen normalisation) and emits a starter yaml with the remainder
// as a commented frequency list for manual review.
func writeDraftYAML(cmd *cobra.Command, counts map[string]int, existing categoryvocab.Vocab, minCount int) error {
	out := cmd.OutOrStdout()

	type entry struct {
		token string
		count int
	}
	var entries []entry
	for t, c := range counts {
		if c >= minCount {
			entries = append(entries, entry{t, c})
		}
	}
	// Sort highest count first so the most-used form becomes canonical.
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].count != entries[j].count {
			return entries[i].count > entries[j].count
		}
		return entries[i].token < entries[j].token
	})

	// normKey: lowercase, spaces and hyphens collapsed, so
	// "Container Orchestration" and "container-orchestration" match.
	normKey := func(t string) string {
		t = strings.ToLower(t)
		t = strings.ReplaceAll(t, " ", "")
		t = strings.ReplaceAll(t, "-", "")
		t = strings.ReplaceAll(t, "_", "")
		return t
	}

	type cluster struct {
		canonical string
		aliases   []string
	}
	byNorm := make(map[string]*cluster)
	order := []string{} // preserves first-seen (highest count) order
	for _, e := range entries {
		k := normKey(e.token)
		if cl, ok := byNorm[k]; ok {
			cl.aliases = append(cl.aliases, e.token)
		} else {
			byNorm[k] = &cluster{canonical: e.token}
			order = append(order, k)
		}
	}

	_, _ = fmt.Fprintln(out, "# categories.yaml — generated by 'dbrain categorize analyze --draft'")
	_, _ = fmt.Fprintln(out, "# Review carefully before running 'dbrain categorize repair'")
	_, _ = fmt.Fprintln(out, "#")
	_, _ = fmt.Fprintln(out, "# ALIASES section: definitive duplicates (same concept, different casing/spacing).")
	_, _ = fmt.Fprintln(out, "# Canonical form is the most-frequent variant.")
	_, _ = fmt.Fprintln(out, "# Manually add further aliases using the frequency list at the bottom.")
	_, _ = fmt.Fprintln(out, "")
	_, _ = fmt.Fprintln(out, "aliases:")

	anyAliases := false
	for _, k := range order {
		cl := byNorm[k]
		if len(cl.aliases) == 0 {
			continue
		}
		anyAliases = true
		_, _ = fmt.Fprintf(out, "  # '%s' (%d)\n", cl.canonical, counts[cl.canonical])
		for _, a := range cl.aliases {
			_, _ = fmt.Fprintf(out, "  \"%s\": \"%s\"  # %d\n", a, cl.canonical, counts[a])
		}
	}
	if !anyAliases {
		_, _ = fmt.Fprintln(out, "  # (none detected — add manually from the frequency list below)")
	}

	_, _ = fmt.Fprintln(out, "")
	_, _ = fmt.Fprintln(out, "# DROP section: tokens to silently remove.")
	_, _ = fmt.Fprintln(out, "# Common candidates: import-source noise, overly generic terms.")
	_, _ = fmt.Fprintln(out, "drop:")
	_, _ = fmt.Fprintln(out, "  # - github-star")
	_, _ = fmt.Fprintln(out, "  # - x-bookmark")
	_, _ = fmt.Fprintln(out, "  # - link-sharing")

	_, _ = fmt.Fprintln(out, "")
	_, _ = fmt.Fprintln(out, "# ── Frequency list (tokens not yet auto-aliased) ──────────────────────────")
	_, _ = fmt.Fprintln(out, "# Use this to spot further aliases and drop candidates.")
	_, _ = fmt.Fprintln(out, "# Copy entries into the aliases/drop sections above, then delete these comments.")
	_, _ = fmt.Fprintln(out, "#")
	_, _ = fmt.Fprintf(out, "# %6s  token\n", "count")
	for _, e := range entries {
		k := normKey(e.token)
		if byNorm[k].canonical != e.token {
			continue // already listed as alias above
		}
		if len(byNorm[k].aliases) > 0 {
			continue // canonical with aliases already listed above
		}
		_, _ = fmt.Fprintf(out, "# %6d  %s\n", e.count, e.token)
	}

	return nil
}
