package app

type envSpec struct {
	Key         string
	ConfigPath  string
	Default     string
	Description string
}

func configEnvSpecs() []envSpec {
	return []envSpec{
		{Key: "DBRAIN_ROOT", ConfigPath: "(env only)", Default: "", Description: "CLI root override. --root wins when both are set."},
		{Key: "DBRAIN_CONFIG_FILE", ConfigPath: "(env only)", Default: "", Description: "CLI config file override. --config-file wins when both are set."},
		{Key: "XDG_CONFIG_HOME", ConfigPath: "(env only)", Default: "~/.config", Description: "Base directory for default config files."},
		{Key: "XDG_DATA_HOME", ConfigPath: "(env only)", Default: "~/.local/share", Description: "Base directory for default database, vault, cache, tmp, and logs."},
		{Key: "GITHUB_TOKEN", ConfigPath: "github.token or env.GITHUB_TOKEN", Default: "", Description: "GitHub API token for importing stars; supports env:, op://, and keychain:// refs."},
		{Key: "DBRAIN_AUTH_ENABLED", ConfigPath: "auth.enabled", Default: "false", Description: "Enable session-gated web UI login. Disabled by default to preserve local-only behavior."},
		{Key: "DBRAIN_AUTH_PROVIDERS", ConfigPath: "auth.providers", Default: "github when auth is enabled", Description: "Comma-separated or YAML-list OAuth providers allowed for web login; currently only github is supported."},
		{Key: "DBRAIN_AUTH_BASE_URL", ConfigPath: "auth.base_url", Default: "http://127.0.0.1:8742", Description: "Public origin used for OAuth callback URLs; must be https for non-localhost auth deployments, for example https://dbrain.example.ts.net."},
		{Key: "DBRAIN_AUTH_SESSION_KEY", ConfigPath: "auth.session_key", Default: "", Description: "Secret key used to sign OAuth state; required when auth is enabled, at least 32 random characters, and supports secret refs."},
		{Key: "DBRAIN_AUTH_GITHUB_CLIENT_ID", ConfigPath: "auth.github.client_id", Default: "", Description: "GitHub OAuth app client ID for web UI login; required when GitHub OAuth is enabled."},
		{Key: "DBRAIN_AUTH_GITHUB_CLIENT_SECRET", ConfigPath: "auth.github.client_secret", Default: "", Description: "GitHub OAuth app client secret for web UI login; required when GitHub OAuth is enabled and supports secret refs."},
		{Key: "DBRAIN_MCP_AUTH_ENABLED", ConfigPath: "mcp.auth.enabled", Default: "false", Description: "Require DB-backed Bearer tokens on MCP Streamable HTTP endpoints. Create tokens with dbrain auth mcp token add NAME."},
		{Key: "DBRAIN_SUMMARY_MODEL / SUMMARIZE_MODEL", ConfigPath: "summary.model", Default: "", Description: "Default model for summarize-backed source and answer synthesis."},
		{Key: "DBRAIN_SUMMARY_LANGUAGE / DBRAIN_OUTPUT_LANGUAGE / SUMMARIZE_LANGUAGE", ConfigPath: "summary.language", Default: "en", Description: "Output language for summaries; use auto to match source language."},
		{Key: "DBRAIN_CATEGORIZE_MODEL", ConfigPath: "categorize.model", Default: "openrouter/google/gemini-2.5-flash", Description: "Default LLM model for item/source categorization."},
		{Key: "DBRAIN_OCR_MODEL / DBRAIN_X_PHOTO_OCR_MODEL", ConfigPath: "ocr.model", Default: "openrouter/google/gemini-3.1-flash-lite-preview", Description: "Default model for X photo OCR."},
		{Key: "DBRAIN_OLLAMA_BASE_URL / OLLAMA_BASE_URL / OLLAMA_HOST", ConfigPath: "ollama.base_url", Default: "http://127.0.0.1:11434", Description: "Ollama endpoint for local model calls."},
		{Key: "DBRAIN_OLLAMA_API_KEY / OLLAMA_API_KEY", ConfigPath: "ollama.api_key", Default: "ollama", Description: "API key label used for Ollama-compatible local calls; supports secret refs."},
		{Key: "DBRAIN_LMSTUDIO_BASE_URL", ConfigPath: "lmstudio.base_url", Default: "http://127.0.0.1:1234/v1", Description: "LM Studio OpenAI-compatible endpoint for local model calls."},
		{Key: "DBRAIN_LMSTUDIO_API_KEY", ConfigPath: "lmstudio.api_key", Default: "lm-studio", Description: "API key label used for LM Studio local calls; supports secret refs."},
		{Key: "DBRAIN_OMLX_BASE_URL", ConfigPath: "omlx.base_url", Default: "http://127.0.0.1:8000/v1", Description: "oMLX OpenAI-compatible endpoint for local model calls, including images when the selected oMLX model supports them."},
		{Key: "DBRAIN_OMLX_API_KEY", ConfigPath: "omlx.api_key", Default: "", Description: "API key for oMLX local calls when oMLX auth is enabled; omitted from Authorization when empty; supports secret refs."},
		{Key: "(config only)", ConfigPath: "llm_backends.<alias>.transport", Default: "openai_chat_completions", Description: "Configured OpenAI-compatible backend alias transport."},
		{Key: "(config only)", ConfigPath: "llm_backends.<alias>.base_url", Default: "", Description: "Configured OpenAI-compatible backend endpoint, for example http://127.0.0.1:8080/v1."},
		{Key: "(config only)", ConfigPath: "llm_backends.<alias>.api_key", Default: "", Description: "Optional API key or secret ref for a configured backend alias."},
		{Key: "(config only)", ConfigPath: "llm_backends.<alias>.local", Default: "false", Description: "Marks a configured backend alias as local for provenance and bakeoff reporting."},
		{Key: "OPENAI_BASE_URL", ConfigPath: "openai.base_url or env.OPENAI_BASE_URL", Default: "", Description: "OpenAI-compatible base URL used by summarize adapter when already exported."},
		{Key: "OPENAI_API_KEY", ConfigPath: "openai.api_key or env.OPENAI_API_KEY", Default: "", Description: "OpenAI-compatible API key used by summarize adapter; supports secret refs."},
		{Key: "OPENAI_USE_CHAT_COMPLETIONS", ConfigPath: "openai.use_chat_completions or env.OPENAI_USE_CHAT_COMPLETIONS", Default: "", Description: "Forces summarize/OpenAI-compatible calls onto chat completions when set."},
		{Key: "DBRAIN_USER_AGENT", ConfigPath: "http.user_agent", Default: "dbrain/<short-sha>", Description: "User-Agent header for outbound API calls; source/web fetching keeps its own fetch headers."},
		{Key: "DBRAIN_METRICS_ENABLED", ConfigPath: "metrics.enabled", Default: "false", Description: "Enable append-only local JSONL metrics for sync all and scheduled sync all runs."},
		{Key: "DBRAIN_METRICS_PATH", ConfigPath: "metrics.path", Default: "<log_dir>/metrics.jsonl", Description: "Metrics JSONL output file; relative paths resolve under log_dir."},
		{Key: "DBRAIN_METRICS_DETAIL", ConfigPath: "metrics.detail", Default: "stage", Description: "Metrics detail level: stage, item, or model_call."},
		{Key: "DBRAIN_METRICS_INCLUDE_SUBJECT_KEYS", ConfigPath: "metrics.include_subject_keys", Default: "false", Description: "Include raw dbrain item/source keys in metrics instead of only deterministic subject hashes."},
		{Key: "DBRAIN_METRICS_STRICT", ConfigPath: "metrics.strict", Default: "false", Description: "Return write failures as command errors after startup succeeds instead of disabling the sink."},
		{Key: "DBRAIN_AUDIT_REQUIRE_SQLITE_BACKUP", ConfigPath: "audit.require.sqlite_backup", Default: "false", Description: "Require remote SQLite backup configuration and freshness in production health audits."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_BOOTSTRAP", ConfigPath: "audit.timeouts.bootstrap", Default: "10s ceiling", Description: "Optional lower production-audit bootstrap deadline; values above the built-in ceiling are clamped."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_LOCAL_QUERY", ConfigPath: "audit.timeouts.local_query", Default: "5s fast / 30s standard", Description: "Optional lower deadline for audit SQLite and local metadata queries."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_METRICS_OR_MANIFEST", ConfigPath: "audit.timeouts.metrics_or_manifest", Default: "10s ceiling", Description: "Optional lower deadline for audit metrics and manifest reads."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_SQLITE_OR_OKF_INTEGRITY", ConfigPath: "audit.timeouts.sqlite_or_okf_integrity", Default: "2m ceiling", Description: "Optional lower deadline for SQLite and OKF integrity checks."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_REMOTE_METADATA", ConfigPath: "audit.timeouts.remote_metadata", Default: "2m ceiling", Description: "Optional lower whole-check deadline for remote archive metadata inspection."},
		{Key: "DBRAIN_AUDIT_TIMEOUT_REMOTE_REQUEST", ConfigPath: "audit.timeouts.remote_request", Default: "30s ceiling", Description: "Optional lower per-request or per-page deadline for remote archive metadata inspection."},
		{Key: "DBRAIN_SCHEDULER_SQLITE_ARCHIVE_ENABLED", ConfigPath: "scheduler.sqlite_archive.enabled", Default: "false", Description: "Declare scheduled SQLite archive durability as enabled and therefore required by production health audits."},
		{Key: "DBRAIN_OPENROUTER_BASE_URL / OPENROUTER_BASE_URL", ConfigPath: "openrouter.base_url", Default: "https://openrouter.ai/api/v1", Description: "OpenRouter API endpoint."},
		{Key: "DBRAIN_OPENROUTER_API_KEY / OPENROUTER_API_KEY", ConfigPath: "openrouter.api_key", Default: "", Description: "OpenRouter API key for hosted LLM/OCR/categorization calls; supports secret refs."},
		{Key: "DBRAIN_OPENROUTER_REFERER / OPENROUTER_HTTP_REFERER", ConfigPath: "openrouter.referer", Default: "https://local.dbrain", Description: "HTTP referer sent to OpenRouter for direct calls."},
		{Key: "DBRAIN_OPENROUTER_TITLE / OPENROUTER_X_TITLE", ConfigPath: "openrouter.title", Default: "dbrain", Description: "HTTP title sent to OpenRouter for direct calls."},
		{Key: "DBRAIN_SOURCE_READER_DOMAINS / DBRAIN_HTTP_READER_DOMAINS", ConfigPath: "source.reader.domains", Default: "canada.ca", Description: "Comma-separated domains routed through the reader/textifier path before summarize."},
		{Key: "DBRAIN_SOURCE_READER_BASE_URL / DBRAIN_HTTP_READER_BASE_URL", ConfigPath: "source.reader.base_url", Default: "https://r.jina.ai/", Description: "Reader/textifier base URL for difficult domains."},
		{Key: "DBRAIN_SOURCE_WAYBACK_ENABLED / DBRAIN_WAYBACK_ENABLED", ConfigPath: "source.wayback.enabled", Default: "true", Description: "Use Internet Archive Wayback as a final source extraction fallback before terminalizing repeated failures."},
		{Key: "DBRAIN_SOURCE_WAYBACK_AVAILABILITY_URL / DBRAIN_WAYBACK_AVAILABILITY_URL", ConfigPath: "source.wayback.availability_url", Default: "https://archive.org/wayback/available?url={escaped_url}", Description: "Wayback Availability API URL template used for final source fallback."},
		{Key: "DBRAIN_FEEDS_ALLOW_PRIVATE_NETWORK / DBRAIN_FEEDS_ALLOW_PRIVATE_NETWORKS", ConfigPath: "feeds.allow_private_network", Default: "false", Description: "Allow feed fetches to localhost/private/link-local IPs for local testing; disabled by default."},
		{Key: "DBRAIN_SYNC_ALL_BROWSER", ConfigPath: "sync_all.browser", Default: "chrome", Description: "Shared browser for cookie-backed X and YouTube imports in manual and scheduled sync all runs."},
		{Key: "DBRAIN_SYNC_ALL_PROFILE", ConfigPath: "sync_all.profile", Default: "", Description: "Optional shared browser profile name or path for cookie-backed imports."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_X_BOOKMARKS", ConfigPath: "sync_all.imports.x_bookmarks", Default: "true", Description: "Include X bookmark import plus X hydration, media transcription, and photo OCR in sync all."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_GITHUB_STARS", ConfigPath: "sync_all.imports.github_stars", Default: "true", Description: "Include GitHub starred repository import in sync all."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_YOUTUBE_WATCH_LATER", ConfigPath: "sync_all.imports.youtube_watch_later", Default: "true", Description: "Include YouTube Watch Later import in sync all."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_YOUTUBE_LIKED", ConfigPath: "sync_all.imports.youtube_liked", Default: "true", Description: "Include liked YouTube video import in sync all."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_FEEDS", ConfigPath: "sync_all.imports.feeds", Default: "true", Description: "Include subscribed RSS, Atom, and JSON Feed imports in sync all."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_APPLE_NOTES", ConfigPath: "sync_all.imports.apple_notes", Default: "apple_notes.enabled", Description: "Shared sync all Apple Notes selection; falls back to apple_notes.enabled when omitted."},
		{Key: "DBRAIN_SYNC_ALL_IMPORT_SAFARI_TABS", ConfigPath: "sync_all.imports.safari_tabs", Default: "safari_tabs.enabled", Description: "Shared sync all Safari tabs selection; falls back to safari_tabs.enabled when omitted."},
		{Key: "DBRAIN_OKF_EXPORT_ENABLED / DBRAIN_SYNC_OKF_EXPORT", ConfigPath: "okf.export.enabled", Default: "false", Description: "Export a full private OKF bundle at the end of sync all; use --skip-okf-export for a one-off opt-out."},
		{Key: "DBRAIN_APPLE_NOTES_ENABLED", ConfigPath: "apple_notes.enabled", Default: "false", Description: "Include Apple Notes import in sync all when enabled; the standalone import command remains explicit."},
		{Key: "DBRAIN_APPLE_NOTES_DB_PATH", ConfigPath: "apple_notes.db_path", Default: "", Description: "Optional Apple Notes NoteStore.sqlite path override."},
		{Key: "DBRAIN_APPLE_NOTES_EXCLUDE_FOLDERS", ConfigPath: "apple_notes.exclude_folders", Default: "", Description: "Comma-separated or YAML-list Apple Notes folders/paths to skip."},
		{Key: "DBRAIN_APPLE_NOTES_EXCLUDE_ACCOUNTS", ConfigPath: "apple_notes.exclude_accounts", Default: "", Description: "Comma-separated or YAML-list Apple Notes accounts to skip."},
		{Key: "DBRAIN_APPLE_NOTES_EXCLUDE_SHARED", ConfigPath: "apple_notes.exclude_shared", Default: "false", Description: "Skip shared Apple Notes during import."},
		{Key: "DBRAIN_APPLE_NOTES_INDEX_ATTACHMENTS", ConfigPath: "apple_notes.index_attachments", Default: "true", Description: "Extract supported Apple Notes attachment files by default."},
		{Key: "DBRAIN_APPLE_NOTES_SKIP_ATTACHMENTS", ConfigPath: "(env only)", Default: "false", Description: "One-off opt-out for Apple Notes attachment file extraction/OCR."},
		{Key: "DBRAIN_APPLE_NOTES_ATTACHMENT_OCR", ConfigPath: "apple_notes.attachment_ocr", Default: "true", Description: "Run local OCR for Apple Notes image attachments when tesseract is available."},
		{Key: "DBRAIN_APPLE_NOTES_SKIP_ATTACHMENT_OCR", ConfigPath: "(env only)", Default: "false", Description: "One-off opt-out for Apple Notes image OCR."},
		{Key: "DBRAIN_APPLE_NOTES_ATTACHMENT_MAX_BYTES", ConfigPath: "apple_notes.attachment_max_bytes", Default: "52428800", Description: "Maximum Apple Notes attachment file size to extract."},
		{Key: "DBRAIN_APPLE_NOTES_TESSERACT_BINARY", ConfigPath: "apple_notes.tesseract_binary", Default: "tesseract", Description: "Local Tesseract binary for Apple Notes image OCR."},
		{Key: "DBRAIN_SAFARI_TABS_ENABLED", ConfigPath: "safari_tabs.enabled", Default: "false", Description: "Include Safari iCloud tabs import in sync all when enabled; the standalone import command remains explicit."},
		{Key: "DBRAIN_SAFARI_TABS_DB_PATH", ConfigPath: "safari_tabs.db_path", Default: "", Description: "Optional Safari CloudTabs.db path override."},
		{Key: "DBRAIN_SAFARI_TABS_DEVICE", ConfigPath: "safari_tabs.device", Default: "", Description: "Safari iCloud device name or UUID to import during sync all."},
		{Key: "DBRAIN_SAFARI_TABS_LIMIT", ConfigPath: "safari_tabs.limit", Default: "0", Description: "Maximum Safari tabs to import after filtering; 0 means all matching tabs."},
		{Key: "DBRAIN_SAFARI_TABS_OLDER_THAN", ConfigPath: "safari_tabs.older_than", Default: "0", Description: "Only import Safari tabs last viewed before this duration ago, for example 168h."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_ENABLED", ConfigPath: "scheduler.sync_all.enabled", Default: "false", Description: "Run sync all periodically from the long-running serve remote process."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_INTERVAL", ConfigPath: "scheduler.sync_all.interval", Default: "1h", Description: "Interval between scheduled sync all runs when the scheduler is enabled."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_RUN_ON_START", ConfigPath: "scheduler.sync_all.run_on_start", Default: "false", Description: "Run sync all once when serve remote starts, then continue on the interval."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_JITTER", ConfigPath: "scheduler.sync_all.jitter", Default: "0", Description: "Optional bounded delay added to each interval so multiple nodes do not sync at exactly the same time."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_BOOKMARKS_LIMIT", ConfigPath: "scheduler.sync_all.x_bookmarks_limit", Default: "0", Description: "Optional scheduled X bookmark import limit for smoke runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_LIMIT", ConfigPath: "scheduler.sync_all.x_limit", Default: "0", Description: "Optional scheduled X hydration limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_MEDIA_LIMIT", ConfigPath: "scheduler.sync_all.x_media_limit", Default: "0", Description: "Optional scheduled X media transcription limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_PHOTO_OCR_LIMIT", ConfigPath: "scheduler.sync_all.x_photo_ocr_limit", Default: "0", Description: "Optional scheduled X photo OCR limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_CONCURRENCY", ConfigPath: "scheduler.sync_all.x_concurrency", Default: "0", Description: "Optional scheduled X hydration concurrency; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_LINK_DISCOVER_LIMIT", ConfigPath: "scheduler.sync_all.link_discover_limit", Default: "0", Description: "Optional scheduled outbound-link discovery limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_LINK_LIMIT", ConfigPath: "scheduler.sync_all.link_limit", Default: "0", Description: "Optional scheduled linked-source enrichment limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_LINK_CONCURRENCY", ConfigPath: "scheduler.sync_all.link_concurrency", Default: "0", Description: "Optional scheduled linked-source enrichment concurrency; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_GITHUB_LIMIT", ConfigPath: "scheduler.sync_all.github_limit", Default: "0", Description: "Optional scheduled GitHub import limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_YOUTUBE_LIMIT", ConfigPath: "scheduler.sync_all.youtube_limit", Default: "0", Description: "Optional scheduled YouTube import limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SOURCE_LIMIT", ConfigPath: "scheduler.sync_all.source_limit", Default: "0", Description: "Optional scheduled source-worker limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SOURCE_CONCURRENCY", ConfigPath: "scheduler.sync_all.source_concurrency", Default: "0", Description: "Optional scheduled source-worker concurrency; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_ARCHIVE_MEDIA_LIMIT", ConfigPath: "scheduler.sync_all.archive_media_limit", Default: "0", Description: "Optional scheduled media archive limit; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_CATEGORIZE_LIMIT", ConfigPath: "scheduler.sync_all.categorize_limit", Default: "0", Description: "Optional scheduled categorization limit per record type; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_CATEGORIZE_CONCURRENCY", ConfigPath: "scheduler.sync_all.categorize_concurrency", Default: "0", Description: "Optional scheduled categorization concurrency; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_CATEGORIZE_TIMEOUT", ConfigPath: "scheduler.sync_all.categorize_timeout", Default: "0", Description: "Optional per-record categorization timeout for scheduled runs; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_TIMEOUT", ConfigPath: "scheduler.sync_all.x_timeout", Default: "0", Description: "Optional scheduled X helper timeout; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_X_MEDIA_DOWNLOAD_TIMEOUT", ConfigPath: "scheduler.sync_all.x_media_download_timeout", Default: "0", Description: "Optional scheduled X media download timeout; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_TIMEOUT", ConfigPath: "scheduler.sync_all.timeout", Default: "0", Description: "Optional scheduled source summary timeout; 0 uses the sync all default."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_OCR_MODEL", ConfigPath: "scheduler.sync_all.ocr_model", Default: "", Description: "Optional scheduled X photo OCR model override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_MODEL", ConfigPath: "scheduler.sync_all.model", Default: "", Description: "Optional scheduled summary model override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_CATEGORIZE_MODEL", ConfigPath: "scheduler.sync_all.categorize_model", Default: "", Description: "Optional scheduled categorization model override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_CLI", ConfigPath: "scheduler.sync_all.cli", Default: "", Description: "Optional scheduled summarize CLI provider override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_LENGTH", ConfigPath: "scheduler.sync_all.length", Default: "", Description: "Optional scheduled summary length override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_BROWSER", ConfigPath: "scheduler.sync_all.browser", Default: "", Description: "Optional scheduled browser override for cookie-backed imports."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_PROFILE", ConfigPath: "scheduler.sync_all.profile", Default: "", Description: "Optional scheduled browser profile override."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_APPLE_NOTES", ConfigPath: "scheduler.sync_all.apple_notes", Default: "false", Description: "Include configured Apple Notes import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SAFARI_TABS", ConfigPath: "scheduler.sync_all.safari_tabs", Default: "false", Description: "Include configured Safari tabs import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_ARCHIVE_MEDIA", ConfigPath: "scheduler.sync_all.archive_media", Default: "false", Description: "Run media archive at the end of scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_FORCE", ConfigPath: "scheduler.sync_all.force", Default: "false", Description: "Force scheduled stages to reprocess existing rows where supported."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_SUMMARIZE", ConfigPath: "scheduler.sync_all.skip_summarize", Default: "false", Description: "Skip summarize-backed source summaries during scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_CATEGORIZE_IMAGES", ConfigPath: "scheduler.sync_all.skip_categorize_images", Default: "false", Description: "Disable image embedding during scheduled categorization, useful for text-only or slow local backends."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_X_BOOKMARKS", ConfigPath: "scheduler.sync_all.skip_x_bookmarks", Default: "false", Description: "Skip X bookmark import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_X", ConfigPath: "scheduler.sync_all.skip_x", Default: "false", Description: "Skip X hydration in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_X_MEDIA", ConfigPath: "scheduler.sync_all.skip_x_media", Default: "false", Description: "Skip X media transcription in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_X_PHOTO_OCR", ConfigPath: "scheduler.sync_all.skip_x_photo_ocr", Default: "false", Description: "Skip X photo OCR in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_LINKS", ConfigPath: "scheduler.sync_all.skip_links", Default: "false", Description: "Skip outbound link discovery and enrichment in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_GITHUB", ConfigPath: "scheduler.sync_all.skip_github", Default: "false", Description: "Skip GitHub import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_YOUTUBE", ConfigPath: "scheduler.sync_all.skip_youtube", Default: "false", Description: "Skip YouTube import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_APPLE_NOTES", ConfigPath: "scheduler.sync_all.skip_apple_notes", Default: "false", Description: "Skip configured Apple Notes import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_SAFARI_TABS", ConfigPath: "scheduler.sync_all.skip_safari_tabs", Default: "false", Description: "Skip configured Safari tabs import in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_FEEDS", ConfigPath: "scheduler.sync_all.skip_feeds", Default: "false", Description: "Skip subscribed feed imports in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_SOURCES", ConfigPath: "scheduler.sync_all.skip_sources", Default: "false", Description: "Skip the final source backlog worker stage in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_CATEGORIZE", ConfigPath: "scheduler.sync_all.skip_categorize", Default: "false", Description: "Skip final categorization in scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_OKF_EXPORT", ConfigPath: "scheduler.sync_all.okf_export", Default: "false", Description: "Export a full private OKF bundle at the end of scheduled sync all runs."},
		{Key: "DBRAIN_SCHEDULER_SYNC_ALL_SKIP_OKF_EXPORT", ConfigPath: "scheduler.sync_all.skip_okf_export", Default: "false", Description: "Skip OKF export for scheduled sync all runs when a broader OKF export setting is enabled."},
		{Key: "DBRAIN_TSNET_WEB", ConfigPath: "tsnet.web", Default: "true", Description: "Mount the read/write web UI when using serve remote."},
		{Key: "DBRAIN_TSNET_MCP", ConfigPath: "tsnet.mcp", Default: "true", Description: "Mount the read-only MCP HTTP endpoint when using serve remote."},
		{Key: "DBRAIN_TSNET_MCP_PATH", ConfigPath: "tsnet.mcp_path", Default: "/mcp", Description: "Remote MCP endpoint path; must be a clean absolute path."},
		{Key: "DBRAIN_TSNET_HOSTNAME", ConfigPath: "tsnet.hostname", Default: "dbrain", Description: "Stable tailnet machine name for the built-in tsnet node."},
		{Key: "DBRAIN_TSNET_STATE_DIR", ConfigPath: "tsnet.state_dir", Default: "<data_dir>/tsnet/<hostname>", Description: "Durable tsnet state directory; must not be synced via iCloud/Dropbox/etc."},
		{Key: "DBRAIN_TSNET_LISTEN", ConfigPath: "tsnet.listen", Default: ":443", Description: "Tailnet listen address for serve remote; default changes to :80 when TLS and Funnel are disabled."},
		{Key: "DBRAIN_TSNET_TLS", ConfigPath: "tsnet.tls", Default: "true", Description: "Use Tailscale HTTPS through tsnet ListenTLS."},
		{Key: "DBRAIN_TSNET_FUNNEL", ConfigPath: "tsnet.funnel", Default: "false", Description: "Expose the tsnet listener through Tailscale Funnel. Requires TLS, a supported port, web auth for web, and MCP bearer auth for MCP."},
		{Key: "DBRAIN_TSNET_STARTUP_TIMEOUT", ConfigPath: "tsnet.startup_timeout", Default: "45s", Description: "Maximum time to wait for tsnet startup and authentication."},
		{Key: "DBRAIN_TSNET_AUTH_KEY", ConfigPath: "tsnet.auth_key", Default: "", Description: "Optional direct Tailscale auth key; prefer a typed secret reference."},
		{Key: "DBRAIN_TSNET_AUTH_KEY_REF", ConfigPath: "tsnet.auth_key_ref", Default: "", Description: "Typed auth key reference: env:, op://, or keychain://."},
		{Key: "DBRAIN_TSNET_ALLOW_SECRET_COMMAND", ConfigPath: "tsnet.allow_secret_command", Default: "false", Description: "Permit YAML-only tsnet.auth_key_command execution."},
		{Key: "DBRAIN_TSNET_ADVERTISE_TAGS", ConfigPath: "tsnet.advertise_tags", Default: "", Description: "Comma-separated Tailscale tags to request for the tsnet node."},
		{Key: "DBRAIN_TSNET_CONTROL_URL", ConfigPath: "tsnet.control_url", Default: "", Description: "Experimental alternate Tailscale control server URL; HTTPS/cert and Funnel behavior may differ."},
		{Key: "DBRAIN_TSNET_VERBOSE", ConfigPath: "tsnet.verbose", Default: "false", Description: "Enable verbose tsnet backend logs."},
		{Key: "DBRAIN_MEDIA_PROXY_BASE_URL / DBRAIN_WEB_BASE_URL", ConfigPath: "media.proxy.base_url", Default: "http://127.0.0.1:8742", Description: "Base URL for local archived-media proxy links in rendered notes and private OKF exports; private OKF export falls back to DBRAIN_AUTH_BASE_URL when these are unset."},
		{Key: "DBRAIN_AUTO_ARCHIVE_MEDIA / DBRAIN_ARCHIVE_AUTO", ConfigPath: "archive.auto", Default: "false", Description: "Run media archive automatically at the end of sync all."},
		{Key: "DBRAIN_ARCHIVE_UPLOAD / DBRAIN_R2_UPLOAD", ConfigPath: "archive.upload", Default: "false", Description: "Upload eligible media before marking/pruning in archive media."},
		{Key: "DBRAIN_ARCHIVE_PROVIDER / DBRAIN_R2_PROVIDER", ConfigPath: "archive.provider", Default: "cloudflare_r2", Description: "Archive provider label."},
		{Key: "DBRAIN_R2_BUCKET / DBRAIN_ARCHIVE_BUCKET / DBRAIN_S3_BUCKET", ConfigPath: "r2.bucket or archive.bucket", Default: "", Description: "S3-compatible bucket for media and SQLite archives."},
		{Key: "DBRAIN_R2_PUBLIC_BASE_URL / DBRAIN_MEDIA_PUBLIC_BASE_URL", ConfigPath: "r2.public_base_url or media.public_base_url", Default: "", Description: "Public base URL for archived media links."},
		{Key: "DBRAIN_R2_ENDPOINT / DBRAIN_S3_ENDPOINT", ConfigPath: "r2.endpoint", Default: "", Description: "S3-compatible endpoint, such as a Cloudflare R2 account endpoint."},
		{Key: "DBRAIN_R2_REGION / DBRAIN_S3_REGION / AWS_REGION / AWS_DEFAULT_REGION", ConfigPath: "r2.region", Default: "auto", Description: "S3-compatible region."},
		{Key: "DBRAIN_R2_ACCESS_KEY_ID / DBRAIN_S3_ACCESS_KEY_ID / AWS_ACCESS_KEY_ID", ConfigPath: "r2.access_key_id", Default: "", Description: "S3-compatible access key ID; supports secret refs."},
		{Key: "DBRAIN_R2_SECRET_ACCESS_KEY / DBRAIN_S3_SECRET_ACCESS_KEY / AWS_SECRET_ACCESS_KEY", ConfigPath: "r2.secret_access_key", Default: "", Description: "S3-compatible secret access key; supports secret refs."},
		{Key: "DBRAIN_R2_SESSION_TOKEN / DBRAIN_S3_SESSION_TOKEN / AWS_SESSION_TOKEN", ConfigPath: "r2.session_token", Default: "", Description: "Optional S3-compatible session token; supports secret refs."},
	}
}
