package app

import (
	"time"

	"github.com/spf13/cobra"

	"github.com/darron/dbrain/internal/mediadownload"
)

func bindSyncAllFlags(cmd *cobra.Command, flags *syncAllFlags) {
	cmd.Flags().IntVar(&flags.xBookmarksLimit, "x-bookmarks-limit", 0, "Optional direct X bookmark import limit for smoke runs")
	cmd.Flags().IntVar(&flags.xLimit, "x-limit", 100, "Maximum X items to hydrate per run")
	cmd.Flags().IntVar(&flags.xMediaLimit, "x-media-limit", 0, "Maximum X items to transcribe per run; 0 uses --x-limit")
	cmd.Flags().IntVar(&flags.xPhotoOCRLimit, "x-photo-ocr-limit", 0, "Maximum X items to OCR per run; 0 uses --x-limit")
	cmd.Flags().IntVar(&flags.xConcurrency, "x-concurrency", 4, "Number of concurrent X post fetches")
	cmd.Flags().DurationVar(&flags.xTimeout, "x-timeout", 30*time.Second, "Timeout for X browser helpers and HTTP requests")
	cmd.Flags().DurationVar(&flags.xMediaTimeout, "x-media-download-timeout", mediadownload.DefaultTimeout, "Timeout for each X or Bluesky media file download; separate from --x-timeout")
	cmd.Flags().StringVar(&flags.ocrModel, "ocr-model", "", "Model override for X and Bluesky photo OCR; supports ollama/<name> and openrouter/<provider>/<model>")
	cmd.Flags().IntVar(&flags.linkDiscoverLimit, "link-discover-limit", 500, "Maximum imported items to scan for outbound links")
	cmd.Flags().IntVar(&flags.linkLimit, "link-limit", 100, "Maximum deduped discovered sources to enrich per link extraction run")
	cmd.Flags().IntVar(&flags.linkConcurrency, "link-concurrency", 4, "Number of concurrent link source extract/summarize jobs")
	cmd.Flags().IntVar(&flags.githubLimit, "github-limit", 0, "Maximum starred repositories to process before stopping")
	cmd.Flags().IntVar(&flags.youtubeLimit, "youtube-limit", 50, "Maximum videos to load from each selected YouTube feed")
	cmd.Flags().BoolVar(&flags.appleNotes, "apple-notes", false, "Include configured Apple Notes import in sync")
	cmd.Flags().StringVar(&flags.appleNotesDBPath, "apple-notes-db", "", "Apple Notes NoteStore.sqlite path override")
	cmd.Flags().IntVar(&flags.appleNotesLimit, "apple-notes-limit", 0, "Maximum Apple Notes to process")
	cmd.Flags().StringArrayVar(&flags.appleNotesExcludeFolders, "apple-notes-exclude-folder", nil, "Exclude an Apple Notes folder/path during sync; repeatable")
	cmd.Flags().StringArrayVar(&flags.appleNotesExcludeAccounts, "apple-notes-exclude-account", nil, "Exclude an Apple Notes account during sync; repeatable")
	cmd.Flags().BoolVar(&flags.appleNotesExcludeShared, "apple-notes-exclude-shared", false, "Exclude shared Apple Notes during sync")
	cmd.Flags().BoolVar(&flags.appleNotesIncludeLocked, "apple-notes-include-locked", false, "Attempt to include password-protected Apple Notes during sync")
	cmd.Flags().BoolVar(&flags.appleNotesSkipAttachments, "apple-notes-skip-attachments", false, "Skip Apple Notes attachment file extraction/OCR during sync")
	cmd.Flags().BoolVar(&flags.appleNotesSkipAttachmentOCR, "apple-notes-skip-attachment-ocr", false, "Skip local OCR for Apple Notes image attachments during sync")
	cmd.Flags().Int64Var(&flags.appleNotesAttachmentMaxBytes, "apple-notes-attachment-max-bytes", 0, "Maximum Apple Notes attachment file size to extract; 0 uses the default")
	cmd.Flags().StringVar(&flags.appleNotesTesseractBinary, "apple-notes-tesseract", "", "Tesseract binary for Apple Notes image OCR")
	cmd.Flags().BoolVar(&flags.safariTabs, "safari-tabs", false, "Include configured Safari iCloud tabs import in sync")
	cmd.Flags().StringVar(&flags.safariTabsDBPath, "safari-tabs-db", "", "Safari CloudTabs.db path override")
	cmd.Flags().StringVar(&flags.safariTabsDevice, "safari-tabs-device", "", "Safari iCloud device name or UUID to import")
	cmd.Flags().IntVar(&flags.safariTabsLimit, "safari-tabs-limit", 0, "Maximum Safari tabs to import after filtering")
	cmd.Flags().DurationVar(&flags.safariTabsOlderThan, "safari-tabs-older-than", 0, "Only import Safari tabs last viewed before this duration ago; 0 imports all matching tabs")
	cmd.Flags().IntVar(&flags.feedLimit, "feed-limit", 100, "Maximum subscribed feeds to check per run")
	cmd.Flags().IntVar(&flags.sourceLimit, "source-limit", 100, "Maximum queued sources to enrich per source-worker batch")
	cmd.Flags().IntVar(&flags.sourceConcurrency, "source-concurrency", 4, "Number of concurrent source extract/summarize jobs per batch")
	cmd.Flags().BoolVar(&flags.blueskyBookmarks, "bluesky-bookmarks", false, "Include the reusable Bluesky bookmark import from the Chrome profile session")
	cmd.Flags().IntVar(&flags.blueskyBookmarksLimit, "bluesky-bookmarks-limit", 0, "Optional Bluesky bookmark import limit for smoke runs")
	cmd.Flags().DurationVar(&flags.blueskyBookmarksTimeout, "bluesky-bookmarks-timeout", 30*time.Second, "Timeout for Bluesky bookmark API requests")
	cmd.Flags().BoolVar(&flags.mastodonBookmarks, "mastodon-bookmarks", false, "Include configured Mastodon bookmark imports")
	cmd.Flags().IntVar(&flags.mastodonBookmarksLimit, "mastodon-bookmarks-limit", 0, "Optional Mastodon bookmark import limit per account")
	cmd.Flags().DurationVar(&flags.mastodonBookmarksTimeout, "mastodon-bookmarks-timeout", 30*time.Second, "Timeout for Mastodon bookmark API requests")
	cmd.Flags().StringVar(&flags.browser, "browser", "", "Preferred browser for X, YouTube, and Bluesky profile-backed flows; defaults to sync_all.browser or chrome")
	cmd.Flags().StringVar(&flags.profile, "profile", "", "Browser profile override for selected profile-backed imports; requires --browser")
	cmd.Flags().BoolVar(&flags.watchLater, "watch-later", true, "Import Watch Later YouTube videos")
	cmd.Flags().BoolVar(&flags.liked, "liked", true, "Import liked YouTube videos")
	cmd.Flags().BoolVar(&flags.watch, "watch", false, "Keep polling the source backlog instead of exiting when drained")
	cmd.Flags().DurationVar(&flags.pollInterval, "poll-interval", 30*time.Second, "How often to poll for new source backlog while watching")
	cmd.Flags().DurationVar(&flags.idleExitAfter, "idle-exit-after", 0, "Optional maximum idle watch duration before exiting")
	cmd.Flags().IntVar(&flags.maxCycles, "max-cycles", 0, "Optional maximum source worker cycles before exiting")
	cmd.Flags().BoolVar(&flags.force, "force", false, "Reprocess existing items and sources, including retrying terminal blocked Mastodon media")
	cmd.Flags().BoolVar(&flags.summarize, "summarize", true, "Run summarize.sh summarization during import and enrichment stages")
	cmd.Flags().StringVar(&flags.model, "model", "", "Optional summarize model override")
	cmd.Flags().StringVar(&flags.cliProvider, "cli", defaultCLIProvider, "Summarize CLI provider")
	cmd.Flags().StringVar(&flags.length, "length", "medium", "Summary length for summarize.sh")
	cmd.Flags().DurationVar(&flags.timeout, "timeout", 5*time.Minute, "Timeout for summarize-backed extraction and summarization stages")
	cmd.Flags().BoolVar(&flags.archiveMedia, "archive-media", false, "Upload finalized media to configured S3-compatible storage and prune local copies at the end of sync")
	cmd.Flags().IntVar(&flags.archiveMediaLimit, "archive-media-limit", 5000, "Maximum finalized media assets to archive at the end of sync")
	cmd.Flags().BoolVar(&flags.okfExport, "okf-export", false, "Export a private OKF bundle after sync completes")
	cmd.Flags().IntVar(&flags.categorizeLimit, "categorize-limit", 0, "Maximum uncategorized items and sources to categorize per record type at the end of sync; 0 means all queued records")
	cmd.Flags().IntVar(&flags.categorizeConcurrency, "categorize-concurrency", 2, "Number of concurrent categorization requests")
	cmd.Flags().StringVar(&flags.categorizeModel, "categorize-model", "", "Categorization model override; defaults to DBRAIN_CATEGORIZE_MODEL or the categorizer default")
	cmd.Flags().DurationVar(&flags.categorizeTimeout, "categorize-timeout", 90*time.Second, "Per-record categorization request timeout")
	cmd.Flags().BoolVar(&flags.categorizeImages, "categorize-images", true, "Embed item photos as base64 for vision-capable categorization models; use --categorize-images=false to disable")
	cmd.Flags().BoolVar(&flags.skipXBookmarks, "skip-x-bookmarks", false, "Skip direct X bookmark import")
	cmd.Flags().BoolVar(&flags.skipX, "skip-x", false, "Skip X hydration")
	cmd.Flags().BoolVar(&flags.skipXMedia, "skip-x-media", false, "Skip X and Bluesky media audio transcription")
	cmd.Flags().BoolVar(&flags.skipXPhotoOCR, "skip-x-photo-ocr", false, "Skip X and Bluesky photo OCR / vision extraction")
	cmd.Flags().BoolVar(&flags.skipLinks, "skip-links", false, "Skip outbound link discovery and enrichment from imported items")
	cmd.Flags().BoolVar(&flags.skipGitHub, "skip-github", false, "Skip GitHub stars import")
	cmd.Flags().BoolVar(&flags.skipYouTube, "skip-youtube", false, "Skip YouTube signal import")
	cmd.Flags().BoolVar(&flags.skipAppleNotes, "skip-apple-notes", false, "Skip configured Apple Notes import")
	cmd.Flags().BoolVar(&flags.skipSafariTabs, "skip-safari-tabs", false, "Skip configured Safari iCloud tabs import")
	cmd.Flags().BoolVar(&flags.skipFeeds, "skip-feeds", false, "Skip RSS/Atom/JSON Feed imports")
	cmd.Flags().BoolVar(&flags.skipSources, "skip-sources", false, "Skip the final source backlog worker stage")
	cmd.Flags().BoolVar(&flags.skipCategorize, "skip-categorize", false, "Skip final item/source categorization")
	cmd.Flags().BoolVar(&flags.skipOKFExport, "skip-okf-export", false, "Skip configured OKF export")
	cmd.Flags().BoolVar(&flags.jsonOut, "json", false, "Print sync stats as JSON")
}
