package store

import "fmt"

func (s *Store) ensureFeedTables() error {
	schema := []string{
		`CREATE TABLE IF NOT EXISTS feeds (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			feed_key TEXT NOT NULL UNIQUE,
			url TEXT NOT NULL,
			normalized_url TEXT NOT NULL UNIQUE,
			resolved_url TEXT NOT NULL DEFAULT '',
			site_url TEXT NOT NULL DEFAULT '',
			title TEXT NOT NULL DEFAULT '',
			description TEXT NOT NULL DEFAULT '',
			language TEXT NOT NULL DEFAULT '',
			enabled INTEGER NOT NULL DEFAULT 1,
			health_status TEXT NOT NULL DEFAULT 'ok',
			poll_interval_seconds INTEGER NOT NULL DEFAULT 3600,
			next_fetch_after TEXT NOT NULL DEFAULT '',
			fetch_etag TEXT NOT NULL DEFAULT '',
			fetch_last_modified TEXT NOT NULL DEFAULT '',
			fetch_body_hash TEXT NOT NULL DEFAULT '',
			last_checked_at TEXT NOT NULL DEFAULT '',
			last_fetched_at TEXT NOT NULL DEFAULT '',
			last_changed_at TEXT NOT NULL DEFAULT '',
			last_success_at TEXT NOT NULL DEFAULT '',
			failure_kind TEXT NOT NULL DEFAULT '',
			first_failed_at TEXT NOT NULL DEFAULT '',
			last_failed_at TEXT NOT NULL DEFAULT '',
			last_http_status INTEGER NOT NULL DEFAULT 0,
			last_error TEXT NOT NULL DEFAULT '',
			error_count INTEGER NOT NULL DEFAULT 0,
			latest_normalized_json TEXT NOT NULL DEFAULT '',
			user_tags TEXT NOT NULL DEFAULT '',
			created_at TEXT NOT NULL,
			updated_at TEXT NOT NULL
		);`,
		`CREATE INDEX IF NOT EXISTS idx_feeds_enabled_health_next ON feeds(enabled, health_status, next_fetch_after);`,
		`CREATE INDEX IF NOT EXISTS idx_feeds_last_success ON feeds(last_success_at);`,
		`CREATE TABLE IF NOT EXISTS feed_fetches (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			feed_id INTEGER NOT NULL,
			observed_at TEXT NOT NULL,
			request_url TEXT NOT NULL,
			final_url TEXT NOT NULL DEFAULT '',
			http_status INTEGER NOT NULL DEFAULT 0,
			headers_json TEXT NOT NULL DEFAULT '',
			content_encoding TEXT NOT NULL DEFAULT '',
			decoded_body_hash TEXT NOT NULL DEFAULT '',
			wire_response_bytes BLOB,
			decoded_size_bytes INTEGER NOT NULL DEFAULT 0,
			parse_status TEXT NOT NULL DEFAULT '',
			parse_error TEXT NOT NULL DEFAULT '',
			FOREIGN KEY(feed_id) REFERENCES feeds(id) ON DELETE CASCADE
		);`,
		`CREATE INDEX IF NOT EXISTS idx_feed_fetches_feed_observed ON feed_fetches(feed_id, observed_at DESC);`,
		`CREATE TABLE IF NOT EXISTS feed_entries (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			feed_id INTEGER NOT NULL,
			entry_key TEXT NOT NULL UNIQUE,
			identity_key TEXT NOT NULL,
			guid TEXT NOT NULL DEFAULT '',
			guid_is_permalink INTEGER NOT NULL DEFAULT 0,
			link TEXT NOT NULL DEFAULT '',
			normalized_link TEXT NOT NULL DEFAULT '',
			title TEXT NOT NULL DEFAULT '',
			author TEXT NOT NULL DEFAULT '',
			published_at TEXT NOT NULL DEFAULT '',
			entry_updated_at TEXT NOT NULL DEFAULT '',
			summary_html TEXT NOT NULL DEFAULT '',
			summary_text TEXT NOT NULL DEFAULT '',
			content_html TEXT NOT NULL DEFAULT '',
			content_markdown TEXT NOT NULL DEFAULT '',
			content_text TEXT NOT NULL DEFAULT '',
			enclosures_json TEXT NOT NULL DEFAULT '[]',
			extensions_json TEXT NOT NULL DEFAULT '{}',
			raw_json TEXT NOT NULL DEFAULT '',
			content_hash TEXT NOT NULL,
			version INTEGER NOT NULL DEFAULT 1,
			item_id INTEGER NOT NULL UNIQUE,
			source_id INTEGER NOT NULL DEFAULT 0,
			first_seen_at TEXT NOT NULL,
			last_seen_at TEXT NOT NULL,
			last_changed_at TEXT NOT NULL,
			created_at TEXT NOT NULL,
			updated_at TEXT NOT NULL,
			FOREIGN KEY(feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
			FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE
		);`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_feed_entries_feed_identity ON feed_entries(feed_id, identity_key);`,
		`CREATE INDEX IF NOT EXISTS idx_feed_entries_feed_seen ON feed_entries(feed_id, last_seen_at);`,
		`CREATE INDEX IF NOT EXISTS idx_feed_entries_normalized_link ON feed_entries(normalized_link);`,
		`CREATE INDEX IF NOT EXISTS idx_feed_entries_source_id ON feed_entries(source_id);`,
		`CREATE TABLE IF NOT EXISTS feed_entry_versions (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			feed_entry_id INTEGER NOT NULL,
			version INTEGER NOT NULL,
			content_hash TEXT NOT NULL,
			raw_json TEXT NOT NULL DEFAULT '',
			link TEXT NOT NULL DEFAULT '',
			normalized_link TEXT NOT NULL DEFAULT '',
			title TEXT NOT NULL DEFAULT '',
			author TEXT NOT NULL DEFAULT '',
			published_at TEXT NOT NULL DEFAULT '',
			entry_updated_at TEXT NOT NULL DEFAULT '',
			content_markdown TEXT NOT NULL DEFAULT '',
			content_html TEXT NOT NULL DEFAULT '',
			content_text TEXT NOT NULL DEFAULT '',
			summary_html TEXT NOT NULL DEFAULT '',
			summary_text TEXT NOT NULL DEFAULT '',
			enclosures_json TEXT NOT NULL DEFAULT '[]',
			extensions_json TEXT NOT NULL DEFAULT '{}',
			observed_at TEXT NOT NULL,
			FOREIGN KEY(feed_entry_id) REFERENCES feed_entries(id) ON DELETE CASCADE
		);`,
		`CREATE INDEX IF NOT EXISTS idx_feed_entry_versions_entry_version ON feed_entry_versions(feed_entry_id, version);`,
	}

	for _, stmt := range schema {
		if _, err := s.db.Exec(stmt); err != nil {
			return fmt.Errorf("apply feed schema: %w", err)
		}
	}
	return nil
}
