package remote

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	scrubAmbientRemoteTestEnv()
	os.Exit(m.Run())
}

func scrubAmbientRemoteTestEnv() {
	for _, key := range []string{
		"DBRAIN_AUTH_BASE_URL",
		"DBRAIN_AUTH_ENABLED",
		"DBRAIN_AUTH_GITHUB_CLIENT_ID",
		"DBRAIN_AUTH_GITHUB_CLIENT_SECRET",
		"DBRAIN_AUTH_PROVIDERS",
		"DBRAIN_AUTH_SESSION_KEY",
		"DBRAIN_MCP_AUTH_ENABLED",
		"DBRAIN_TSNET_ADVERTISE_TAGS",
		"DBRAIN_TSNET_ALLOW_SECRET_COMMAND",
		"DBRAIN_TSNET_AUTH_KEY",
		"DBRAIN_TSNET_AUTH_KEY_COMMAND",
		"DBRAIN_TSNET_AUTH_KEY_REF",
		"DBRAIN_TSNET_CONTROL_URL",
		"DBRAIN_TSNET_FUNNEL",
		"DBRAIN_TSNET_HOSTNAME",
		"DBRAIN_TSNET_LISTEN",
		"DBRAIN_TSNET_MCP",
		"DBRAIN_TSNET_MCP_PATH",
		"DBRAIN_TSNET_STARTUP_TIMEOUT",
		"DBRAIN_TSNET_STATE_DIR",
		"DBRAIN_TSNET_TLS",
		"DBRAIN_TSNET_VERBOSE",
		"DBRAIN_TSNET_WEB",
	} {
		_ = os.Unsetenv(key)
	}
}
